local_directory:    /Users/stefan/Documents/projects/alhalqa/erzaehlbox/demo_content
finished_directory: /Users/stefan/Documents/projects/alhalqa/erzaehlbox/done
hostname:           providence.dev
upload_directory:   /home/mediaupload/erzaehlbox
